---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepstack-deployment
  labels:
    app: deepstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepstack
  template:
    metadata:
      labels:
        app: deepstack
    spec:
      containers:
        - name: deepstack
          image: deepquestai/deepstack
          env:
            - name: VISION-SCENE
              value: "true"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          volumeMounts:
          - mountPath: /datastore
            name: deepstack-data
            subPath: datastore
          imagePullPolicy: IfNotPresent
      volumes:
      - name: deepstack-data
        persistentVolumeClaim:
          claimName: deepstack-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deepstack-pvc
  namespace: default
  labels:
    app: deepstack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: deepstack-service
  labels:
    app: deepstack
spec:
  ports:
  - port: 80
    targetPort: 5000
    name: http
  selector:
    app: deepstack