---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freeipa-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freeipa
  template:
    metadata:
      labels:
        app: freeipa
    spec:
      containers:
        - name: freeipa
          image: freeipa/freeipa-server:fedora-30
          env:
          - name: IPA_SERVER_HOSTNAME
            value: ipa.internal.lazz.tech
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: freeipa
                key: admin.password
          - name: IPA_SERVER_INSTALL_OPTS
            value: "-U -r LAZZ.TECH --setup-dns --no-forwarders --no-ntp"
          resources:
            requests:
              memory: "1024Mi"
              cpu: "100m"
            limits:
              memory: "1200Mi"
              cpu: "500m"
          # readinessProbe:
          #   exec:
          #     command: [ "/usr/bin/systemctl", "status", "ipa" ]
          #   initialDelaySeconds: 60
          #   timeoutSeconds: 10
          #   periodSeconds: 10
          #   successThreshold: 1
          #   failureThreshold: 3
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 443
            protocol: TCP
          - containerPort: 53
            protocol: UDP
          - containerPort: 88
            protocol: TCP
          - containerPort: 88
            protocol: UDP
          volumeMounts:
          - mountPath: /data
            name: freeipa-data
            subPath: data
          - name: cgroups
            mountPath: /sys/fs/cgroup
            readOnly: true
          - mountPath: /usr/share/ipa/ipa-rewrite.conf.template
            name: freeipa-httpd-config
            subPath: ipa-rewrite.conf.template
          imagePullPolicy: IfNotPresent
      volumes:
      - name: freeipa-data
        persistentVolumeClaim:
          claimName: freeipa-pvc
      - name: cgroups
        hostPath:
          path: /sys/fs/cgroup
      - name: freeipa-httpd-config
        configMap:
            name: freeipa-httpd-config
            items:
              - key: ipa-rewrite.conf.template
                path: ipa-rewrite.conf.template
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freeipa-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: freeipa-service
spec:
  ports:
  - port: 80
    targetPort: 80
    name: tcp
  selector:
    app: freeipa
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: freeipa-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  tls:
    - secretName: internal-acme-crt-secret
      hosts:
        - '*.internal.lazz.tech'
  rules:
  - host: ipa.internal.lazz.tech
    http:
      paths:
      - backend:
          serviceName: freeipa-service
          servicePort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: freeipa-httpd-config
data:
  ipa-rewrite.conf.template: |
    # VERSION 6 - DO NOT REMOVE THIS LINE

    RewriteEngine on

    # By default forward all requests to /ipa. If you don't want IPA
    # to be the default on your web server comment this line out.
    ${AUTOREDIR}RewriteRule ^/$$ https://$FQDN/ipa/ui [L,NC,R=301]

    # Redirect to the fully-qualified hostname. Not redirecting to secure
    # port so configuration files can be retrieved without requiring SSL.
    RewriteCond %{HTTP_HOST}    !^$FQDN$$ [NC]
    RewriteRule ^/ipa/(.*)      http://$FQDN/ipa/$$1 [L,R=301]

    # Redirect to the secure port if not displaying an error or retrieving
    # configuration.
    #
    # THESE LINES SHOULD BE COMMENTED OUT TO AVOID INFINITE REDIRECT BEHIND
    # EXTERNAL SSL REVERSE PROXY
    #
    # RewriteCond %{SERVER_PORT}  !^443$$
    # RewriteCond %{REQUEST_URI}  !^/ipa/(errors|config|crl)
    # RewriteCond %{REQUEST_URI}  !^/ipa/[^\?]+(\.js|\.css|\.png|\.gif|\.ico|\.woff|\.svg|\.ttf|\.eot)$$
    # RewriteRule ^/ipa/(.*)      https://$FQDN/ipa/$$1 [L,R=301,NC]

    # Rewrite for plugin index, make it like it's a static file
    RewriteRule ^/ipa/ui/js/freeipa/plugins.js$$    /ipa/wsgi/plugins.py [PT]