---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocy-deployment
  labels:
    app: grocy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grocy
  template:
    metadata:
      labels:
        app: grocy
    spec:
      containers:
        - name: grocy
          image: ghcr.io/linuxserver/grocy
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          volumeMounts:
          - mountPath: /config
            name: grocy-data
            subPath: config
          imagePullPolicy: IfNotPresent
      volumes:
      - name: grocy-data
        persistentVolumeClaim:
          claimName: grocy-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grocy-pvc
  namespace: default
  labels:
    app: grocy
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: grocy-service
  labels:
    app: grocy
spec:
  ports:
  - port: 80
    targetPort: 80
    name: tcp
  selector:
    app: grocy
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: grocy-ingress
  labels:
    app: grocy
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  tls:
    - secretName: internal-acme-crt-secret
      hosts:
        - '*.internal.lazz.tech'
  rules:
  - host: grocy.internal.lazz.tech
    http:
      paths:
      - backend:
          serviceName: grocy-service
          servicePort: 80